projects:
  drsalesapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        graphQLApiId: eefr2ulv75cdrat7ry3ynr4xse
      endpoints:
        prod: >-
          https://yshlny3u7fc2tlx4alub5cxpk4.appsync-api.us-east-1.amazonaws.com/graphql
